vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("x", "<leader>p", "\"_dP")
vim.keymap.set("n", "<leader>y", "\"+y")
vim.keymap.set("v", "<leader>y", "\"+y")
vim.keymap.set("n", "<leader>Y", "\"+Y")
vim.keymap.set("n", "<leader>s", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
vim.keymap.set("n", "<leader>rp", ":w<CR>:term python %<CR>")
vim.keymap.set("n", "<leader>r3", ":w<CR>:term python3 %<CR>")
vim.keymap.set("n", "<leader>rh", ":w<CR>: !open %<CR>")
--vim.keymap.set("n", "<leader>ct", ":w<CR>:! tsc %<CR>")
vim.keymap.set("n", "<leader>cj", "I//<Esc>")
vim.keymap.set("n", "<leader>ch", "I<!-- <Esc>A --><Esc>")
vim.keymap.set("n", "<leader>cl", "I/* <Esc>A */<Esc>")
vim.keymap.set("n", "<leader>cp", "I# <Esc>")
vim.keymap.set("n", "<leader>rch", "_xxxxx$xxxx")
vim.keymap.set("n", "<leader>rcp", "_xx")
vim.keymap.set("n", "<leader>i", "I<Tab><Esc>")
vim.keymap.set("n", "<leader>coc", ":! clang % -o ")
vim.keymap.set("n", "<leader>cop", ":! clang++ % -o ")
vim.keymap.set("n", "<leader>gpp", ":! g++ % -Wall -o ")
vim.keymap.set("n", "<leader>cb", ":term cargo build<CR>")
vim.keymap.set("n", "<leader>cr", ":term cargo run<CR>")
vim.keymap.set("n", "<leader>cc", ":term cargo check<CR>")
vim.keymap.set("n", "<leader>ct", ":term cargo test<CR>")
vim.keymap.set("n", "<leader>gr", ":term go run .<CR>")
